'use strict';

module.exports = {
  ADD_NODE: 0,
  DELETE_NODE: 1,
  SELECT_NODE: 2,
  DESELECT_NODE: 3,
  ADD_EDGE: 4,
  CLEAR_MAP: 5,
  SET_INITIAL_X_POSITION: 6,
  SET_TERMINAL_X_POSITION: 7,
  SET_INITIAL_Y_POSITION: 8,
  SET_TERMINAL_Y_POSITION: 9,
  SET_IMAGE_URL: 10,
  SET_IMAGE_WIDTH: 11,
  SET_IMAGE_HEIGHT: 12,
  SET_IMAGE_OFFSET: 13,
  SET_SIMULATION_COORDINATES: 14,
  START_SIMULATION: 15
};
